POST /_index_template/challenges_template
Content-Type: application/json

{
  "index_patterns": [
    "challenges*"
  ],
  "priority": 1,
  "template": {
    "settings": {
      "index.default_pipeline": "add-timestamp"
    },
    "mappings": {
      "properties": {
        "title": {
          "type": "keyword",
          "index_options": "docs",
          "index": false,
          "norms": false
        },
        "description": {
          "type": "keyword",
          "index_options": "docs",
          "index": false,
          "norms": false
        },
        "idealRequest": {
          "type": "keyword",
          "index_options": "docs",
          "index": false,
          "norms": false
        },
        "indexSettings": {
          "type": "keyword",
          "index_options": "docs",
          "index": false,
          "norms": false
        },
        "challengeTests": {
          "type": "keyword",
          "index_options": "docs",
          "index": false,
          "norms": false
        },
        "examples": {
          "type": "object",
          "dynamic": false,
          "properties": {
            "testDataJson": {
              "type": "keyword",
              "index_options": "docs",
              "index": false,
              "norms": false
            },
            "expectedResult": {
              "type": "keyword",
              "index_options": "docs",
              "index": false,
              "norms": false
            },
            "explanation": {
              "type": "keyword",
              "index_options": "docs",
              "index": false,
              "norms": false
            }
          }
        }
      }
    }
  }
}