services:
  elasticsearch:
    image: elasticsearch:8.14.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -i http://localhost:9200"
        ]
      interval: 10s
      timeout: 10s
      retries: 3

  kibana:
    depends_on:
      elasticsearch:
        condition: service_healthy
    image: kibana:8.14.1
    volumes:
      - kibana_data:/usr/share/kibana/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 FOUND'"
        ]
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
  set-up-es:
    depends_on:
      elasticsearch:
        condition: service_healthy
    build: .
volumes:
  data:
    driver: local
  kibana_data:
    driver: local